### ISSUE TITLE
注册密钥是多少呀

### ISSUE THREAD

**Issue by civetming** [AlbertLin0923/mango-i18n-system#1]

**Comment by AlbertLin0923** [comment]
注册密钥 在 server配置里面，默认是“mango-i18n-system-register-key”；源码位置：https://github.com/AlbertLin0923/mango-i18n-system/blob/cd8f1c3776b7de114b54af64ec4dc16e19a0ec58/packages/server/system.config.js#L10 ，你可以fork代码后自定义该密钥，建议管理员保存该密钥注册账号，然后其他用户通过管理员在系统以手工添加的方式新增
