### ISSUE TITLE
请问如何运行项目 进行本地开发调试

### ISSUE THREAD

**Issue by GeminiKnight** [AlbertLin0923/mango-i18n-system#16]
同上

**Comment by AlbertLin0923** [comment]
可以这样本地调试：
1. clone 代码到本地
2. cd 到项目根目录，执行 pnpm i，安装依赖包
3. cd 到 packages/server ，执行pnpm dev ，启动服务端
4. cd 到 packages/client，执行pnpm dev，启动客户端
5. 根据命令行的提示，这时候打开 http://localhost:5006 即可看到项目已经启动了

**Comment by GeminiKnight** [comment]
最新的server代码里,.env缺少一些环境变量，会导致启动报错
![image](https://github.com/user-attachments/assets/f4a673be-975a-4aaa-b2ba-64368d07c6d6)

**Comment by GeminiKnight** [comment]
更新仓库配置的代码，为什么是先 checkout 到resolveGitBranchName，不是应该先 `git pull origin ${resolveGitBranchName}`，再 `git checkout ${resolveGitBranchName}` 么？
![image](https://github.com/user-attachments/assets/279de44a-3961-4c9d-a2d9-5ab4269699ec)
