### ISSUE TITLE
请问在本地开发怎么运行呢

### ISSUE THREAD

**Issue by jinxxxxxi** [AlbertLin0923/mango-i18n-system#17]

**Comment by AlbertLin0923** [comment]
可以这样本地运行：

1. clone 项目代码到本地
2. cd 到项目根目录，执行 pnpm i，安装依赖包
3. cd 到 packages/server ，执行pnpm dev ，启动服务端
4. cd 到 packages/client，执行pnpm dev，启动客户端
5. 根据命令行的提示，这时候打开 http://localhost:5006/ 即可看到项目已经启动了😄
