### ISSUE TITLE
语言包列表报错

### ISSUE THREAD

**Issue by civetming** [AlbertLin0923/mango-i18n-system#2]
![image](https://github.com/AlbertLin0923/mango-i18n-system/assets/44012892/434b2d48-f1b4-46a0-ad9c-158e43731512)

**Comment by AlbertLin0923** [comment]
抱歉，刚看到，看这个报错信息，应该是 https://github.com/AlbertLin0923/mango-i18n-system/blob/cd8f1c3776b7de114b54af64ec4dc16e19a0ec58/packages/server/src/modules/setting/setting.service.ts#L195 这里报错了，获取不到 gitAccessToken，你检查一下设置里面的“git仓库访问令牌”，是否有输入（并输入正确的gitlab token）

**Comment by civetming** [comment]
好的 已经解决 谢谢了

**Comment by AlbertLin0923** [comment]
done
