### ISSUE TITLE
新的问题执行 yarn run updateLocale 报错

### ISSUE THREAD

**Issue by lik778** [AlbertLin0923/mango-i18n-system#3]
(base) baixing@likuandeMacBook-Air chato-www-ts % yarn run updateLocale
yarn run v1.22.19
$ i18n-scripts updateLocale -f http://localhost:3000/api/locale/get_locale_map -o ./src/locales/common/ -l zh-CN en-US id-ID
/Users/baixing/Desktop/baixing-workspace/chato-www-ts/node_modules/@mango-scripts/i18n-scripts/bin/i18n-scripts.js:24
const updater = require('update-notifier')
                ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/baixing/Desktop/baixing-workspace/chato-www-ts/node_modules/update-notifier/index.js from /Users/baixing/Desktop/baixing-workspace/chato-www-ts/node_modules/@mango-scripts/i18n-scripts/bin/i18n-scripts.js not supported.
Instead change the require of index.js in /Users/baixing/Desktop/baixing-workspace/chato-www-ts/node_modules/@mango-scripts/i18n-scripts/bin/i18n-scripts.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/baixing/Desktop/baixing-workspace/chato-www-ts/node_modules/@mango-scripts/i18n-scripts/bin/i18n-scripts.js:24:17) {
  code: 'ERR_REQUIRE_ESM'
}

**Comment by lik778** [comment]
@AlbertLin0923

**Comment by lik778** [comment]
Node 版本 18.8

**Comment by AlbertLin0923** [comment]
抱歉，最近公司事情多，才看到。这个问题应该是 @mango-scripts/i18n-scripts 的依赖包 update-notifier 的 6.x 版本不再支持 commonjs 导致的，你尝试降级 @mango-scripts/i18n-scripts 到 1.0.2 试试 （如可用则锁定该版本） @lik778

**Comment by AlbertLin0923** [comment]
done
