### ISSUE TITLE
系统不能正常运行

### ISSUE THREAD

**Issue by islixuebo** [AlbertLin0923/mango-i18n-system#4]
docker 运行nginx报错
api程序报错，页面出不来

**Comment by AlbertLin0923** [comment]
你是什么报错呢？我刚才本地重新构建&启动，是没有问题的，方便贴报错截图吗？

**Comment by AlbertLin0923** [comment]
> docker 运行nginx报错 api程序报错，页面出不来

你是什么报错呢？我刚才本地重新构建&启动，是没有问题的，方便贴报错截图吗
